name: Pull Request

on:
  pull_request:
    branches: [ "main" ]
jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Install Dependencies
        working-directory: atlas.com/<%= resourceName %>
        run: go mod download
      - name: Build the Go Application
        working-directory: atlas.com/<%= resourceName %>
        run: |
          go mod tidy
          go mod download
          go build ./...
      - name: Run Tests
        working-directory: atlas.com/<%= resourceName %>
        run: go test -v ./...
